name: "Chromatic"

on: push

jobs:
    chromatic:
        name: Run Chromatic
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              working-directory: ./WebClient
              run: npm ci
            - name: Run Chromatic
              uses: chromaui/action@latest
              working-directory: ./WebClient
              with:
                  workingDir: ./WebClient
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  zip: true
                  onlyChanged: true
