name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              working-directory: ./WebClient
              run: npm ci
            - name: build production project
              working-directory: ./WebClient
              run: npm run build
            - name: linting typescript
              working-directory: ./WebClient
              run: npm run lint:ts
            - name: linting scss
              working-directory: ./WebClient
              run: npm run lint:scss
    # visual_tests:
    #     name: Run Chromatic
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4
    #           with:
    #               fetch-depth: 0
    #         - uses: actions/setup-node@v4
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #         - name: Install dependencies
    #           working-directory: ./WebClient
    #           run: npm ci
    #         - name: Run Chromatic
    #           working-directory: ./WebClient
    #           uses: chromaui/action@latest
    #           with:
    #               projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
