name: client
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              working-directory: ./WebClient
              run: npm ci
            - name: build production project
              working-directory: ./WebClient
              run: npm run build
            - name: linting typescript
              working-directory: ./WebClient
              run: npm run lint:ts
            - name: linting scss
              working-directory: ./WebClient
              run: npm run lint:scss
            - name: test unit
              working-directory: ./WebClient
              run: npm run test:unit
